### ISSUE TITLE
Weird blinking on ground

### ISSUE THREAD

**Issue by Kerbinator-Fras** [Its-Just-Luci/EVO#1]
![UAIMBGYM71@WYK_ $12Q96B](https://user-images.githubusercontent.com/55748582/108500655-17604c00-72eb-11eb-8b63-b4131d09c1ab.jpg)
When close to the ground on some far satelites of gas giants, significant blinking can be seen.
It is not like the pattern of farm patch bug (as RSS issue#217 shows), and blinking is related to the angle of view relative to the planet.

**Comment by Kerbinator-Fras** [comment]
Mod related: EVO32k alpha 0.1 with EVO-folder TUFX
and EVE 1.8.1-2
RSS v18.1.3 with KSP 1.8.1 and Kopernicus-1.8.1-34

**Comment by Its-Just-Luci** [comment]
I don't believe this is an EVO issue, as none of the gas giants nor their moons have been modified from RSSVE yet
