### ISSUE TITLE
Uranus's rings are completely white

### ISSUE THREAD

**Issue by LilBread402** [Its-Just-Luci/EVO#10]
I downloaded the mods after only having RSS and its dependencies installed, then installed EVO without any of the conflicting mods installed and the mod worked fine and looks very nice. But a problem I found is Uranus's rings are completely white and black.

**Comment by LilBread402** [comment]
I also use RSS in 1.11.2 if that helps

**Comment by Its-Just-Luci** [comment]
> I also use RSS in 1.11.2 if that helps

this is not a supported version, sadly

**Comment by Its-Just-Luci** [comment]
closing issue for now out of a lack of info, logs, or pictures.

**Comment by pckbls** [comment]
EVO references [RSS-Textures/PluginData/UranusRing.png](https://github.com/Its-Just-Luci/EVO/blob/main/65536%20-%2064k/EVO64K%20for%20RSS/GameData/EVO/Configs/Misc_Configs/Kopernicus/RSS-Tweaks/Uranus-Rings.cfg#L16) which is not (or no longer?) part of upstream `RSS-Textures`.

You can obtain said texture file from [this particular Merge Request](https://github.com/KSP-RO/RSS-Textures/pull/45) and drop it into `RSS-Textures/PluginData`. It works just fine for me. I'm also running KSP 1.11.2.

Kind regards
Patrick

**Comment by pckbls** [comment]
@Its-Just-Luci I have just noticed that `UranusRing.png` exists in the EVO code repository but for some odd reason is not included in the release ZIP files. The latter only includes the `MarsColor.dds` texture.
