### ISSUE TITLE
Cloud desyncing 

### ISSUE THREAD

**Issue by Its-Just-Luci** [Its-Just-Luci/EVO#11]
Clouds desync due to apparent differences in rotational speed, this will be on the "fix later" list for the time being

**Comment by Baguette420** [comment]
![KSP_x64_3JtjciPR5s](https://user-images.githubusercontent.com/87278491/125947651-638610a3-ed71-4645-bf63-277c75a66d41.jpg)

Is that what is causing the blurry/duplicated cloud textures I have here. Apart from that it looks amazing.

**Comment by Sadaell** [comment]
I think I managed to fix it by small changes in the rotation speed around the y-axis. Every cloud layer rotates on a circle of radius = planet radius + layer altitude. In your config all layers have the same speed of 15m/s, so the upper layers begin to lag behind the lower layers with time

**Comment by Bellabong** [comment]
> I think I managed to fix it by small changes in the rotation speed around the y-axis. Every cloud layer rotates on a circle of radius = planet radius + layer altitude. In your config all layers have the same speed of 15m/s, so the upper layers begin to lag behind the lower layers with time

This is correct.

All one has to do is calculate the distance (circumference of Earth/Kerbin radius + altitude) that each cloud layer has to travel and then adjust the speeds accordingly. Stays in sync even after 30 years

**Comment by Baguette420** [comment]
What exactly do I need to edit and to what value?

**Comment by ballisticfox** [comment]
Okay so I did the math and the formula is
r is the radius of the body
h₁ is the height of the first layer
h₂ is the height of the second layer
s is known speed
x is the unknown speed

(2pi(r+h₁))/x=(2pi(r+h₂))/s

**Comment by Noiredd** [comment]
You have to match velocities according to the formula above but also offsets. Here is my config:
```
	OBJECT
	{
		name = EarthCloudsHigh
		body = Earth
		speed = 0,15,0
		offset = 0,180,180
		altitude = 25000
```
```
	OBJECT
	{
		name = EarthCloudsMedium
		body = Earth
		speed = 0,14.98358348968110,0
		altitude = 18000
		offset = 0,180,180
```
```
	OBJECT
	{
		name = EarthCloudsLow
		body = Earth
		speed = 0,14.9507504690432000,0
		altitude = 4000
		offset = 0,180,180
```
```
	OBJECT
	{
		name = EarthCloudsShadow
		body = Earth
		altitude = 2100
		speed = 0,14.9462945590994000,0
		detailSpeed = 0,4.9820981863664800,0  // no idea what this does though
		offset = 0,180,181
```
Clouds perfectly synced, looking beautiful.

I'd submit a PR with this but alas, somehow the config in the repo looks completely different than the one in the release... @Its-Just-Luci is this intended?

**Comment by Its-Just-Luci** [comment]
ok, sorry to like... be an ass?

![image](https://github.com/Its-Just-Luci/EVO/assets/57868183/b539a78f-cb11-4b60-8ccc-7032a9fb6d72)

I last _touched_ this repo over two years ago. It is left here for archival purposes and nothing more. I'm retired, sorry

That said, feel free to fork and make another "active" version, just not in the issues on this repo.

**Comment by Noiredd** [comment]
FYI: GitHub has a dedicated archival feature for old and inactive repositories. Go to your [repo settings](https://github.com/Its-Just-Luci/EVO/settings), scroll all the way down to the "danger zone", and here it is:
![archive](https://github.com/Its-Just-Luci/EVO/assets/17203018/33e85e7f-2cc7-469f-bf61-7cbc3d4be46c)
