### ISSUE TITLE
Daytime city lights

### ISSUE THREAD

**Issue by Kerbinator-Fras** [Its-Just-Luci/EVO#2]
In daytime, the city lights is still on

Mod related: EVO32k alpha 0.1 with EVO-folder TUFX
and EVE 1.8.1-2
RSS v18.1.3 with KSP 1.8.1 and Kopernicus-1.8.1-34

**Comment by Its-Just-Luci** [comment]
I believe this has to do w the empty texture I was using, it's not an issue in the latest version I am running (what will become EVO 0.2) so expect this to be fixed soon™

**Comment by Its-Just-Luci** [comment]
Fixed in 0.1b, city day texture has replaced it
