### ISSUE TITLE
How To fix the Bootprints and Kopernicus Patch

### ISSUE THREAD

**Issue by vader111** [Its-Just-Luci/EVO#8]
@Its-Just-Luci
EVO\Configs\Misc_Configs\Kopernicus.cfg
Need to change @Kopernicus:FOR[EVO]:NEEDS[RealSolarSystem] to @Kopernicus:AFTER[RealSolarSystem]

EVO\Configs\Misc_Configs\Kopernicus\Bootprints

Need to change @Kopernicus:AFTER[Kopernicus] to @Kopernicus:AFTER[RealSolarSystem] in both Mars and Moon cfgs

**Comment by Its-Just-Luci** [comment]
Noted, going to unify the bootprint configs into one file in the next patch, closing bc it will be fixed in 0.3

**Comment by Its-Just-Luci** [comment]
Reopening so I remember to do this next week, I am forgetful and things slip by from time to time 😛

**Comment by Its-Just-Luci** [comment]
fixed in 0.3-RC-2
