### ISSUE TITLE
Saturn shadows

### ISSUE THREAD

**Issue by si2504** [Its-Just-Luci/EVO#9]
Saturn body doesn't cast its own shadow on its rings and doesn't block sunlight from reaching it's moons when they are behind saturn.

**Comment by Its-Just-Luci** [comment]
Saturn casts shadow on it's rings in my local install, so I have either accidentally fixed the issue, or you have something installed incorrectly

![screenshot126](https://user-images.githubusercontent.com/57868183/119278477-25c04b80-bbeb-11eb-8b64-28b408bb5d9c.png)
